[tool.poetry]
name = "meli-position-finder"
version = "0.1.0"
description = ""
authors = ["Eric Kohan <ekohan@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.28.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
